package com.example.demo;

import org.springframework.security.core.context.SecurityContextImpl;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;
import util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /user (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	UserRepository userRepository;

	@Autowired
	private UserService userService;



    //register
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String password) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		String MD5Password = MD5Util.getMD5(password);

		User n = new User();
		n.setName(name);
		n.setPassword(MD5Password);
		userService.save(n);

		return "Saved";
	}

	// login
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public @ResponseBody String userLogin(ModelMap map, @RequestParam String name, @RequestParam String password,HttpServletRequest request) {
		if (name.equals("") || password.equals("")) {
			map.addAttribute("error", "please input");
			return "login";
		}
		String MD5Password = MD5Util.getMD5(password);
		User user = userService.findUserByNameAndPassword(name, MD5Password);
		if (user == null) {
			map.addAttribute("error", "wrong information");
			return "login";
		} else {

			HttpSession session = request.getSession();
			session.setAttribute("name",name);
			return "success";
//			return "redirect:/index";
		}
	}


	@GetMapping(path = "/logout")
	public String logoutPage(ModelMap map, HttpServletRequest request) {

		request.getSession().removeAttribute("name");
//		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
//		if (auth != null) {
//
//			SecurityContextHolder.getContext().setAuthentication(null);
//		}
		map.addAttribute("logout", "safely");
		return "/login";
	}


	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userService.findAll();
	}

	private User getCurrentUser(HttpServletRequest request) {

		String name = (String)request.getSession().getAttribute("name");
		User userEntity = userService.findByName(name);
		return userEntity;


	}
}
